CREATE TABLE "ATRIBUTO" (
	"ID"	TEXT NOT NULL,
	"DESCRIPCION"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE "BASE" (
	"PACK"	TEXT NOT NULL,
	"ID"	TEXT NOT NULL,
	"TIPO"	TEXT NOT NULL,
	"DESCRIPCION"	TEXT NOT NULL,
	"FAMILIA"	TEXT NOT NULL,
	"SECCION"	TEXT NOT NULL,
	"PV1"	NUMERIC NOT NULL,
	"PV2"	NUMERIC NOT NULL,
	"PV3"	NUMERIC NOT NULL,
	"ATRIBUTO"	TEXT NOT NULL,
	"VALOR_ATRIBUTO"	TEXT NOT NULL,
	"PEDIDO_MINIMO"	INTEGER NOT NULL,
	PRIMARY KEY("ID","TIPO","PACK")
);
CREATE TABLE "COMPOSICION" (
	"ID"	TEXT NOT NULL,
	"BASE"	TEXT NOT NULL,
	"TIPO"	TEXT NOT NULL,
	"CANTIDAD"	NUMERIC NOT NULL,
	PRIMARY KEY("ID","BASE","TIPO")
);
CREATE TABLE "DISEÑO" (
	"PACK"	TEXT NOT NULL,
	"ID"	TEXT NOT NULL,
	"NOMBRE"	TEXT NOT NULL,
	PRIMARY KEY("ID","PACK")
);
CREATE TABLE "FAMILIA" (
	"ID"	TEXT NOT NULL,
	"DESCRIPCION"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE "LOCALIDAD" (
	"ID"	TEXT NOT NULL,
	"NOMBRE"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE "PROD_COMPOSICION" (
	"ID"	TEXT NOT NULL,
	"DESCRIPCION"	TEXT NOT NULL,
	"PRECIO"	NUMERIC NOT NULL DEFAULT 0,
	PRIMARY KEY("ID")
);
CREATE TABLE "PUEBLO" (
	"ID"	TEXT NOT NULL,
	"NOMBRE"	TEXT NOT NULL,
	"LOCALIDAD"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE "REL_ATRIBUTO" (
	"ID"	TEXT NOT NULL,
	"ATRIBUTO"	TEXT NOT NULL,
	"NOMBRE"	TEXT NOT NULL,
	PRIMARY KEY("ID","ATRIBUTO")
);
CREATE TABLE "SECCION" (
	"ID"	TEXT NOT NULL,
	"DESCRIPCION"	TEXT NOT NULL,
	"UBICACION"	TEXT,
	PRIMARY KEY("ID")
);
CREATE TABLE "TARIFA" (
	"PACK"	TEXT,
	"ID"	TEXT NOT NULL,
	"BASE"	TEXT NOT NULL,
	"TIPO"	TEXT NOT NULL,
	"PRECIO"	NUMERIC NOT NULL DEFAULT 0.0,
	PRIMARY KEY("BASE","ID","TIPO","PACK")
);